### ISSUE TITLE
 A lot of  [debug] Sendgrid webhook (deferred) but no bounces processed

### ISSUE THREAD

**Issue by yurg** [aghstrategies/com.aghstrategies.airmail#35]
Hi, we use this extension on Drupal 7.98 / CiviCRM 5.65 (php 7.4) and not quite sure our bounces are being processed.
There are a lot of [debug] messages ( like [debug] Sendgrid webhook (deferred) ) in civicrm logs, however random checks of emails mentioned in debug messages shows no emails are on hold. At the same time we get sad statistics of mailings deliverability from SendGrid, some 75%  of success delivery, however civicrm mailing report shows, say,   33 (0.06%) bounces - and senddrid support points to high volume of bounces in mailings, much more than 0.06% 
Do we miss something in the extension configuration - there seem to be none but generated webhook url? 
How do we debug? Cheers.

**Comment by BOTKevinS** [comment]
Not sure if its related, but one of our clients has been unable to send any Mosaico mailings ever since we upgraded to the latest CiviCRM ESR 5.63.4 yesterday.  If we disable the Airmail exension, the mailings are sent (but no longer processing bounces of course).  Not sure what the path forward is here.  Thanks.

Kevin

**Comment by yurg** [comment]
@BOTKevinS Cheers, that's another one I'm afraid - our issue has started earlier than CiviCRM ESR 5.63.4 But you never know..

**Comment by BOTKevinS** [comment]
Is anyone monitoring these issues?

**Comment by elisseck** [comment]
@BOTKevinS these issues are minimally monitored, all on volunteer time. I think your issue is unrelated to this one, but i'd definitely need more information (error log, backtrace, whatever it is when mailings fail to go out only when airmail is on) to be helpful to you. If you'd like to open an new issue with more information, i'd be happy to review it when I am able.

@yurg you'll see a "deferred" log when Sendgrid sends back that notice. You can read more about Sendgrid "deferred" status here: https://support.sendgrid.com/hc/en-us/articles/360041316874-Email-Delivery-Deferral. It's not technically a bounce so it is not recorded as such.

It SOUNDS like the webhook is reporting back to your CiviCRM correctly if you're seeing deferred notices, at least. Have you configured that http post in Sendgrid to send the bounce notices as well as the deferred ones? I'm afraid without more information I can't be too much more helpful but it does sound like you're having some deliverability issues from Sendgrid that can be confounding. 

I would:

- Check `/sites/default/files/civicrm/ConfigAndLog` (or wherever your Civi logs are) for any AirMail related notices or errors. Those could report on things that we can help fix.
- Check your Sendgrid suppression list under "Suppressions" and spot check the "Bounce" list for events you think didn't come thru. That could give you timestamps to look at Backdrop logs, Civi logs, server logs to see what might be stopping those webhook notifications from going thru. If it's a sendgrid problem, i'm afraid there isn't much we can do.

**Comment by yurg** [comment]
@elisseck Thank you, back to this after quite some time: it seems to be working, however is hard to tell which one of extensions does the job. 
Have both Sendgrid and Airmail installed and configured with respective counterpart hooks configured via https://app.sendgrid.com/settings/mail_settings/webhook_settings
