### ISSUE TITLE
SMTP2GO 

### ISSUE THREAD

**Issue by netzih** [aghstrategies/com.aghstrategies.airmail#7]
Can this somehow work with SMTP2GO?
I put the webhooks in and their developers are saying that the webhooks were successfully received but they were translated as a delivery instead of a bounce.
Thank you

**Comment by agh1** [comment]
The framework is designed so that it could handle webhooks from any SMTP provider, but the structure of the actual webhook message will be different from provider to provider.  The only handlers that it currently has are Sendgrid and SES.  The handler basically needs to get the key information from the notification and then pass that along to the appropriate action (bounce, spam report, etc.).

We're very open to adding backends if you'd like to write one or sponsor one.  The goal of this extension was to unify as much as possible since most of the SMTP extensions were doing the same thing, just interpreting different webhook formats.

**Comment by netzih** [comment]
Got it,
How difficult is it to write one?
What would I need from the developers at SMTP2GO?

**Comment by agh1** [comment]
It's not terribly difficult if you're comfortable with PHP and understand the premise of the webhook.  I don't think the SMTP2GO developers would have anything to do with this, but you'd get the format of the webhook from their documentation and ideally generate a few samples using a postbin.  Then, you'd produce something like https://github.com/aghstrategies/com.aghstrategies.airmail/blob/master/CRM/Airmail/Backend/Ses.php or https://github.com/aghstrategies/com.aghstrategies.airmail/blob/master/CRM/Airmail/Backend/Sendgrid.php that appends additional data to the outbound messages and retrieves the data from the webhook.

**Comment by netzih** [comment]
The documentation is at https://support.smtp2go.com/hc/en-gb/articles/223087967-Setting-Up-Webhooks
Might be above my level of expertise.
What would it take to sponsor it?

**Comment by agh1** [comment]
I think we could do it for $750.  If you'd like to go ahead with this, just open a request at https://civi911.com .  It'll be more than the $225 call fee, but we can just bill for the remainder once we're done.
